// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package compute

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsDomainAlreadyExisted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == DomainAlreadyExisted_DOMAIN_ALREADY_EXISTED.String() && e.Code == 409
}

func ErrorDomainAlreadyExisted(format string, args ...interface{}) *errors.Error {
	return errors.New(409, DomainAlreadyExisted_DOMAIN_ALREADY_EXISTED.String(), fmt.Sprintf(format, args...))
}
