// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/compute/compute.proto

package compute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInstanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VCpuNum     uint64 `protobuf:"varint,2,opt,name=vCpuNum,proto3" json:"vCpuNum,omitempty"`
	Memory      uint64 `protobuf:"varint,3,opt,name=Memory,proto3" json:"Memory,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateInstanceReq) Reset() {
	*x = CreateInstanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInstanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceReq) ProtoMessage() {}

func (x *CreateInstanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceReq.ProtoReflect.Descriptor instead.
func (*CreateInstanceReq) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInstanceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInstanceReq) GetVCpuNum() uint64 {
	if x != nil {
		return x.VCpuNum
	}
	return 0
}

func (x *CreateInstanceReq) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CreateInstanceReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateInstanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateInstanceReply) Reset() {
	*x = CreateInstanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInstanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceReply) ProtoMessage() {}

func (x *CreateInstanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceReply.ProtoReflect.Descriptor instead.
func (*CreateInstanceReply) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{1}
}

type DeleteInstanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteInstanceReq) Reset() {
	*x = DeleteInstanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInstanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceReq) ProtoMessage() {}

func (x *DeleteInstanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceReq.ProtoReflect.Descriptor instead.
func (*DeleteInstanceReq) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{2}
}

type DeleteInstanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteInstanceReply) Reset() {
	*x = DeleteInstanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteInstanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceReply) ProtoMessage() {}

func (x *DeleteInstanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceReply.ProtoReflect.Descriptor instead.
func (*DeleteInstanceReply) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{3}
}

//****************************** StoragePool Messages ***********************************
type CreateStoragePoolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateStoragePoolReq) Reset() {
	*x = CreateStoragePoolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStoragePoolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoragePoolReq) ProtoMessage() {}

func (x *CreateStoragePoolReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoragePoolReq.ProtoReflect.Descriptor instead.
func (*CreateStoragePoolReq) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{4}
}

type CreateStoragePoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateStoragePoolReply) Reset() {
	*x = CreateStoragePoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStoragePoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoragePoolReply) ProtoMessage() {}

func (x *CreateStoragePoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoragePoolReply.ProtoReflect.Descriptor instead.
func (*CreateStoragePoolReply) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{5}
}

type DeleteStoragePoolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteStoragePoolReq) Reset() {
	*x = DeleteStoragePoolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStoragePoolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoragePoolReq) ProtoMessage() {}

func (x *DeleteStoragePoolReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoragePoolReq.ProtoReflect.Descriptor instead.
func (*DeleteStoragePoolReq) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{6}
}

type DeleteStoragePoolReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteStoragePoolReply) Reset() {
	*x = DeleteStoragePoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_compute_compute_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStoragePoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoragePoolReply) ProtoMessage() {}

func (x *DeleteStoragePoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_compute_compute_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoragePoolReply.ProtoReflect.Descriptor instead.
func (*DeleteStoragePoolReply) Descriptor() ([]byte, []int) {
	return file_api_compute_compute_proto_rawDescGZIP(), []int{7}
}

var File_api_compute_compute_proto protoreflect.FileDescriptor

var file_api_compute_compute_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2f, 0x63, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7b, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x43,
	0x70, 0x75, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x43, 0x70,
	0x75, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x15,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x22, 0x18, 0x0a, 0x16, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x9f, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x49, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f,
	0x6c, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x6f,
	0x6f, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x72, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2f, 0x6d, 0x61, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x3b, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_compute_compute_proto_rawDescOnce sync.Once
	file_api_compute_compute_proto_rawDescData = file_api_compute_compute_proto_rawDesc
)

func file_api_compute_compute_proto_rawDescGZIP() []byte {
	file_api_compute_compute_proto_rawDescOnce.Do(func() {
		file_api_compute_compute_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_compute_compute_proto_rawDescData)
	})
	return file_api_compute_compute_proto_rawDescData
}

var file_api_compute_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_compute_compute_proto_goTypes = []interface{}{
	(*CreateInstanceReq)(nil),      // 0: v1.CreateInstanceReq
	(*CreateInstanceReply)(nil),    // 1: v1.CreateInstanceReply
	(*DeleteInstanceReq)(nil),      // 2: v1.DeleteInstanceReq
	(*DeleteInstanceReply)(nil),    // 3: v1.DeleteInstanceReply
	(*CreateStoragePoolReq)(nil),   // 4: v1.CreateStoragePoolReq
	(*CreateStoragePoolReply)(nil), // 5: v1.CreateStoragePoolReply
	(*DeleteStoragePoolReq)(nil),   // 6: v1.DeleteStoragePoolReq
	(*DeleteStoragePoolReply)(nil), // 7: v1.DeleteStoragePoolReply
}
var file_api_compute_compute_proto_depIdxs = []int32{
	0, // 0: v1.Compute.CreateDomain:input_type -> v1.CreateInstanceReq
	2, // 1: v1.Compute.DeleteDomain:input_type -> v1.DeleteInstanceReq
	4, // 2: v1.Compute.CreateStoragePool:input_type -> v1.CreateStoragePoolReq
	6, // 3: v1.Compute.DeleteStoragePool:input_type -> v1.DeleteStoragePoolReq
	1, // 4: v1.Compute.CreateDomain:output_type -> v1.CreateInstanceReply
	3, // 5: v1.Compute.DeleteDomain:output_type -> v1.DeleteInstanceReply
	5, // 6: v1.Compute.CreateStoragePool:output_type -> v1.CreateStoragePoolReply
	7, // 7: v1.Compute.DeleteStoragePool:output_type -> v1.DeleteStoragePoolReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_compute_compute_proto_init() }
func file_api_compute_compute_proto_init() {
	if File_api_compute_compute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_compute_compute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInstanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_compute_compute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInstanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_compute_compute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInstanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_compute_compute_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteInstanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_compute_compute_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStoragePoolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_compute_compute_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStoragePoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_compute_compute_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStoragePoolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_compute_compute_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStoragePoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_compute_compute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_compute_compute_proto_goTypes,
		DependencyIndexes: file_api_compute_compute_proto_depIdxs,
		MessageInfos:      file_api_compute_compute_proto_msgTypes,
	}.Build()
	File_api_compute_compute_proto = out.File
	file_api_compute_compute_proto_rawDesc = nil
	file_api_compute_compute_proto_goTypes = nil
	file_api_compute_compute_proto_depIdxs = nil
}
