// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: api/system/system_error.proto

package system

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserUnknownErrors int32

const (
	UserUnknownErrors_UNKNOWN_ERROR  UserUnknownErrors = 0
	UserUnknownErrors_INTERNAL_ERROR UserUnknownErrors = 1
)

// Enum value maps for UserUnknownErrors.
var (
	UserUnknownErrors_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "INTERNAL_ERROR",
	}
	UserUnknownErrors_value = map[string]int32{
		"UNKNOWN_ERROR":  0,
		"INTERNAL_ERROR": 1,
	}
)

func (x UserUnknownErrors) Enum() *UserUnknownErrors {
	p := new(UserUnknownErrors)
	*p = x
	return p
}

func (x UserUnknownErrors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserUnknownErrors) Descriptor() protoreflect.EnumDescriptor {
	return file_api_system_system_error_proto_enumTypes[0].Descriptor()
}

func (UserUnknownErrors) Type() protoreflect.EnumType {
	return &file_api_system_system_error_proto_enumTypes[0]
}

func (x UserUnknownErrors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserUnknownErrors.Descriptor instead.
func (UserUnknownErrors) EnumDescriptor() ([]byte, []int) {
	return file_api_system_system_error_proto_rawDescGZIP(), []int{0}
}

type UserNotFoundErrors int32

const (
	UserNotFoundErrors_USER_NOT_FOUND UserNotFoundErrors = 0
)

// Enum value maps for UserNotFoundErrors.
var (
	UserNotFoundErrors_name = map[int32]string{
		0: "USER_NOT_FOUND",
	}
	UserNotFoundErrors_value = map[string]int32{
		"USER_NOT_FOUND": 0,
	}
)

func (x UserNotFoundErrors) Enum() *UserNotFoundErrors {
	p := new(UserNotFoundErrors)
	*p = x
	return p
}

func (x UserNotFoundErrors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserNotFoundErrors) Descriptor() protoreflect.EnumDescriptor {
	return file_api_system_system_error_proto_enumTypes[1].Descriptor()
}

func (UserNotFoundErrors) Type() protoreflect.EnumType {
	return &file_api_system_system_error_proto_enumTypes[1]
}

func (x UserNotFoundErrors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserNotFoundErrors.Descriptor instead.
func (UserNotFoundErrors) EnumDescriptor() ([]byte, []int) {
	return file_api_system_system_error_proto_rawDescGZIP(), []int{1}
}

type UserConflictError int32

const (
	UserConflictError_USER_CONFLICT UserConflictError = 0
)

// Enum value maps for UserConflictError.
var (
	UserConflictError_name = map[int32]string{
		0: "USER_CONFLICT",
	}
	UserConflictError_value = map[string]int32{
		"USER_CONFLICT": 0,
	}
)

func (x UserConflictError) Enum() *UserConflictError {
	p := new(UserConflictError)
	*p = x
	return p
}

func (x UserConflictError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserConflictError) Descriptor() protoreflect.EnumDescriptor {
	return file_api_system_system_error_proto_enumTypes[2].Descriptor()
}

func (UserConflictError) Type() protoreflect.EnumType {
	return &file_api_system_system_error_proto_enumTypes[2]
}

func (x UserConflictError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserConflictError.Descriptor instead.
func (UserConflictError) EnumDescriptor() ([]byte, []int) {
	return file_api_system_system_error_proto_rawDescGZIP(), []int{2}
}

type UserUnAuthorizedError int32

const (
	UserUnAuthorizedError_UNAUTHORIZED             UserUnAuthorizedError = 0
	UserUnAuthorizedError_PASSWORD_INCORRECT_ERROR UserUnAuthorizedError = 1
)

// Enum value maps for UserUnAuthorizedError.
var (
	UserUnAuthorizedError_name = map[int32]string{
		0: "UNAUTHORIZED",
		1: "PASSWORD_INCORRECT_ERROR",
	}
	UserUnAuthorizedError_value = map[string]int32{
		"UNAUTHORIZED":             0,
		"PASSWORD_INCORRECT_ERROR": 1,
	}
)

func (x UserUnAuthorizedError) Enum() *UserUnAuthorizedError {
	p := new(UserUnAuthorizedError)
	*p = x
	return p
}

func (x UserUnAuthorizedError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserUnAuthorizedError) Descriptor() protoreflect.EnumDescriptor {
	return file_api_system_system_error_proto_enumTypes[3].Descriptor()
}

func (UserUnAuthorizedError) Type() protoreflect.EnumType {
	return &file_api_system_system_error_proto_enumTypes[3]
}

func (x UserUnAuthorizedError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserUnAuthorizedError.Descriptor instead.
func (UserUnAuthorizedError) EnumDescriptor() ([]byte, []int) {
	return file_api_system_system_error_proto_rawDescGZIP(), []int{3}
}

var File_api_system_system_error_proto protoreflect.FileDescriptor

var file_api_system_system_error_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x40, 0x0a,
	0x11, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x2a,
	0x2e, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xa0, 0x45, 0x94, 0x03, 0x2a,
	0x2c, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e,
	0x46, 0x4c, 0x49, 0x43, 0x54, 0x10, 0x00, 0x1a, 0x04, 0xa0, 0x45, 0xa6, 0x03, 0x2a, 0x4d, 0x0a,
	0x15, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48,
	0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x41, 0x53, 0x53,
	0x57, 0x4f, 0x52, 0x44, 0x5f, 0x49, 0x4e, 0x43, 0x4f, 0x52, 0x52, 0x45, 0x43, 0x54, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x1a, 0x04, 0xa0, 0x45, 0x91, 0x03, 0x42, 0x33, 0x50, 0x01,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x72,
	0x73, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x6d, 0x61, 0x72, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x3b, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_system_system_error_proto_rawDescOnce sync.Once
	file_api_system_system_error_proto_rawDescData = file_api_system_system_error_proto_rawDesc
)

func file_api_system_system_error_proto_rawDescGZIP() []byte {
	file_api_system_system_error_proto_rawDescOnce.Do(func() {
		file_api_system_system_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_system_system_error_proto_rawDescData)
	})
	return file_api_system_system_error_proto_rawDescData
}

var file_api_system_system_error_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_system_system_error_proto_goTypes = []interface{}{
	(UserUnknownErrors)(0),     // 0: user.v1.UserUnknownErrors
	(UserNotFoundErrors)(0),    // 1: user.v1.UserNotFoundErrors
	(UserConflictError)(0),     // 2: user.v1.UserConflictError
	(UserUnAuthorizedError)(0), // 3: user.v1.UserUnAuthorizedError
}
var file_api_system_system_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_system_system_error_proto_init() }
func file_api_system_system_error_proto_init() {
	if File_api_system_system_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_system_system_error_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_system_system_error_proto_goTypes,
		DependencyIndexes: file_api_system_system_error_proto_depIdxs,
		EnumInfos:         file_api_system_system_error_proto_enumTypes,
	}.Build()
	File_api_system_system_error_proto = out.File
	file_api_system_system_error_proto_rawDesc = nil
	file_api_system_system_error_proto_goTypes = nil
	file_api_system_system_error_proto_depIdxs = nil
}
