version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos
    env_file:
      - ./nacos_conf/nacos-standlone-mysql.env
    volumes:
      - /Users/zgh/data/nacos/standalone-logs/:/home/nacos/logs
      - /Users/zgh/data/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    restart: always
    env_file:
      - ./nacos_conf/mysql.env
    volumes:
      - /Users/zgh/data/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  apisix-dashboard:
    container_name: apisix-dashboard
    image: apache/apisix-dashboard:2.10.1-alpine
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9527:9000"

  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    hostname: myRabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /Users/zgh/data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin


  apisix:
    container_name: apisix
    image: apache/apisix:2.12.1-alpine
    restart: always
    volumes:
      - /Users/zgh/data/apisix_log:/usr/local/apisix/logs
      - ../docker/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
      - "9092:9092"


  etcd:
    container_name: etcd
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - /Users/zgh/data/etcd_data:/bitnami/etcd/data
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"


  redis:
    container_name: redis
    restart: always
    image: redis:6
    volumes:
      - /Users/zgh/data/redis_data:/data
      - ./redis_conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /Users/zgh/data/redis_logs:/logs
    ports:
      - "6379:6379"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos


  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_conf/provisioning:/etc/grafana/provisioning
      - ./grafana_conf/dashboards:/var/lib/grafana/dashboards
      - ./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini


  system:
    container_name: system
    build: ../app/system
    volumes:
      - ../docker/system_conf:/data/system/conf
    restart: always
    depends_on:
      - nacos

  auth:
    container_name: auth
    build: ../app/auth
    volumes:
      - ../docker/auth_conf:/data/auth/conf
    restart: always
    depends_on:
      - nacos

  mars-ui:
    container_name: mars-ui
    build: ../app/mars-ui/docker
    restart: always
    external_links:
      - apisix
    ports:
      - "80:80"
    depends_on:
      - system
      - auth
