#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos
    env_file:
      - ./nacos_conf/nacos-standlone-mysql.env
    volumes:
      - /opt/nacos/standalone-logs/:/home/nacos/logs
      - /opt/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
    networks:
      - db
      - app


  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    restart: always
    env_file:
      - ./nacos_conf/mysql.env
    volumes:
      - /opt/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db
      - app


  apisix-dashboard:
    container_name: apisix-dashboard
    image: apache/apisix-dashboard:2.10.1-alpine
    restart: always
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
    - "9000:9000"
    networks:
      - db
      - app

  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    hostname: myRabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /opt/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - db
      - app

  apisix:
    container_name: apisix
    image: apache/apisix:2.12.1-alpine
    restart: always
    volumes:
      - /opt/apisix/apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
      - "9092:9092"
    networks:
      - db
      - app

  etcd:
    container_name: etcd
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - /opt/etcd:/mars/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    networks:
      - db
      - app

  redis:
    container_name: redis
    restart: always
    image: redis:6
    volumes:
      - /opt/redis/data:/data
      - ./redis_conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /opt/redis/logs:/logs
    ports:
      - "6379:6379"
    networks:
      - db
      - app

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    networks:
      - db
      - app

  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_conf/provisioning:/etc/grafana/provisioning
      - ./grafana_conf/dashboards:/var/lib/grafana/dashboards
      - ./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - db
      - app


networks:
  db:
    driver: bridge
  app:
    driver: bridge