version: "3"
services:
  sys:
    container_name: sys
    build: ../app/sys
    volumes:
      - ./system_conf:/opt/mars/sys/conf
    restart: always
    ports:
      - "8004:8004"
      - "9004:9004"
    networks:
      - app
      - db



networks:
  app:
    driver: bridge
  db:
    driver: bridge

volumes:
  etcd_data:
    driver: local
