version: '3.9'
services:
  ui:
    image: potatozgh/mars-ui:v1.0.2
    ports:
      - protocol: tcp
        published: 80
        target: 80
        mode: host
    networks:
      - app_net
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

networks:
  app_net:
    driver: overlay
    attachable: true

