version: '3.9'
services:
  mon-node1:
    image: ceph/daemon:latest-luminous
    volumes:
      - type: bind
        target: /etc/ceph
        source: /etc/ceph
        read_only: false
      - type: bind
        target: /var/lib/
        source: /var/lib/
        read_only: false
      - type: bind
        target: /var/log/ceph
        source: /var/log/ceph
        read_only: false
    networks:
      - host
    environment:
      - MON_IP=192.168.128.4
      - CEPH_PUBLIC_NETWORK=192.168.128.0/24
    command:
      - mon
    deploy:
      placement:
        constraints:
          - "node.labels.name==node1"
      replicas: 1
      restart_policy:
        condition: any
  mon-node2:
    image: ceph/daemon:latest-luminous
    volumes:
      - type: bind
        target: /etc/ceph
        source: /etc/ceph
        read_only: false
      - type: bind
        target: /var/lib/
        source: /var/lib/
        read_only: false
      - type: bind
        target: /var/log/ceph
        source: /var/log/ceph
        read_only: false
    networks:
      - host
    environment:
      - MON_IP=192.168.128.5
      - CEPH_PUBLIC_NETWORK=192.168.128.0/24
    command:
      - mon
    deploy:
      placement:
        constraints:
          - "node.labels.name==node2"
      replicas: 1
      restart_policy:
        condition: any
  mon-node3:
    image: ceph/daemon:latest-luminous
    volumes:
      - type: bind
        target: /etc/ceph
        source: /etc/ceph
        read_only: false
      - type: bind
        target: /var/lib/
        source: /var/lib/
        read_only: false
      - type: bind
        target: /var/log/ceph
        source: /var/log/ceph
        read_only: false
    environment:
      - MON_IP=192.168.128.6
      - CEPH_PUBLIC_NETWORK=192.168.128.0/24
    networks:
      - host
    command:
      - mon
    deploy:
      placement:
        constraints:
          - "node.labels.name==node3"
      replicas: 1
      restart_policy:
        condition: any
  osd-node1:
    image: ceph/daemon:latest-luminous
    networks:
      - host
    depends_on:
      - mon-node1
    environment:
      - CLUSTER=ceph
      - WEIGHT=1.0
      - MON_NAME=mon-node1
      - MON_IP=192.168.128.4
      - OSD_TYPE=directory
    command:
      - osd
    volumes:
      - type: bind
        target: /var/lib/ceph/
        source: /var/lib/ceph/
        read_only: false
      - type: bind
        target: /etc/ceph
        source: /etc/ceph
        read_only: false
      - type: bind
        target: /var/lib/ceph/osd
        source: /var/lib/ceph/osd
        read_only: false
      - type: bind
        target: /etc/localtime:ro
        source: /etc/localtime
        read_only: false
    deploy:
      placement:
        constraints:
          - "node.labels.name==node1"
      replicas: 1
      restart_policy:
        condition: any
  osd-node2:
    image: ceph/daemon:latest-luminous
    networks:
      - host
    depends_on:
      - mon-node2
    environment:
      - CLUSTER=ceph
      - WEIGHT=1.0
      - MON_NAME=mon-node1
      - MON_IP=192.168.128.5
      - OSD_TYPE=directory
    command:
      - osd
    volumes:
      - type: bind
        target: /var/lib/ceph/
        source: /var/lib/ceph/
        read_only: false
      - type: bind
        target: /etc/ceph
        source: /etc/ceph
        read_only: false
      - type: bind
        target: /var/lib/ceph/osd
        source: /var/lib/ceph/osd
        read_only: false
      - type: bind
        target: /etc/localtime:ro
        source: /etc/localtime
        read_only: false
    deploy:
      placement:
        constraints:
          - "node.labels.name==node2"
      replicas: 1
      restart_policy:
        condition: any
  osd-node3:
    image: ceph/daemon:latest-luminous
    networks:
      - host
    depends_on:
      - mon-node3
    environment:
      - CLUSTER=ceph
      - WEIGHT=1.0
      - MON_NAME=mon-node1
      - MON_IP=192.168.128.6
      - OSD_TYPE=directory
    command:
      - osd
    volumes:
      - type: bind
        target: /var/lib/ceph/
        source: /var/lib/ceph/
        read_only: false
      - type: bind
        target: /etc/ceph
        source: /etc/ceph
        read_only: false
      - type: bind
        target: /var/lib/ceph/osd
        source: /var/lib/ceph/osd
        read_only: false
      - type: bind
        target: /etc/localtime:ro
        source: /etc/localtime
        read_only: false
    deploy:
      placement:
        constraints:
          - "node.labels.name==node3"
      replicas: 1
      restart_policy:
        condition: any
  mgr-master:
    image: ceph/daemon:latest-luminous
    networks:
      - host
    environment:
      - CLUSTER=ceph
    command:
      - mgr
    depends_on:
      - mon-node1
    volumes:
      - type: bind
        target: /etc/ceph
        source: /etc/ceph
        read_only: false
      - type: bind
        target: /var/lib/ceph/
        source: /var/lib/ceph/
        read_only: false
    deploy:
      placement:
        constraints: [ node.role==manager ]
      replicas: 1
      restart_policy:
        condition: any

networks:
  host:
    external:
      name: host
  db_net:
