version: '3.9'
services:
  ui:
    image: potatozgh/mars-ui:v1.0.1-beat
    ports:
      - protocol: tcp
        published: 80
        target: 80
        mode: host
    networks:
      - proxy_net
      - app_net
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==task"

networks:
  app_net:
  proxy_net: