version: '3.9'
services:
  chief:
    image: potatozgh/chief:v1.0.1
    volumes:
      - ./chief_conf:/data/cell/conf
    depends_on:
      - nacos
      - system
    networks:
      - app_net
      - db_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  db_net:
    driver: overlay
    attachable: true
  app_net:
    driver: overlay
    attachable: true
