version: '3.9'
services:
  auth:
    image: potatozgh/auth:v1.0.1-beat
    volumes:
      - ./auth_conf:/data/auth/conf
    depends_on:
      - nacos
      - system
    networks:
      - app_net
      - db_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app_net:
    driver: overlay
    attachable: true
  db_net:
    driver: overlay
    attachable: true