// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/mars-projects/mars/app/chief/internal/server"
	"github.com/mars-projects/mars/app/chief/internal/service"
	"github.com/mars-projects/mars/app/chief/internal/task"
	"github.com/mars-projects/mars/common/wire/sender"
	"github.com/mars-projects/mars/common/wire/transaction"
	"github.com/mars-projects/mars/conf"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	transactionEngine := transaction.NewTransactionEngine()
	messageSender := sender.NewMessageSender()
	taskManager, err := task.NewTaskManager(transactionEngine, messageSender)
	if err != nil {
		return nil, nil, err
	}
	imageService := service.NewImageService(taskManager)
	httpServer := server.NewHTTPServer(confServer, imageService, logger)
	grpcServer := server.NewGRPCServer(confServer, imageService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
