server:
  name: mars.chief.service
  version: 1.0.0
  http:
    addr: 0.0.0.0:8002
    timeout: 2s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    password: "970312"
    db: 1
auth:
  key: some-secret-key
  client_id: test
  client_secret: test
  access_expired: 3600
  refresh_expired: 7200